### ISSUE TITLE
When using OMP atom order is not always the same

### ISSUE THREAD

**Issue by jfikar** [pierrehirel/atomsk#17] opened 2019-12-03 14:40 UTC
Dear Pierre,

I found another thing, which makes reproducibility of my polycrystalline calculations more difficult. When I create a polycrystal twice from the same file, the result is identical, but the order of atoms in the file is somehow random. This in general shouldn't be a problem, but in my LAMMPS elastic calculation there is:

`displace_atoms all random ${atomjiggle} ${atomjiggle} ${atomjiggle} ${seed} units box`

which displaces the atoms by small amount and if the seed number is the same, the calculation should be completely reproducible. But in fact it is not, as the atom order changes.

I think it is due to OMP. For now I use as a workaround OMP_NUM_THREADS=1, but then the calculations are slower.

Is there another way to keep the order of atoms deterministic? I thought about sorting the atom at the end like -sort x, but it may not always work, as there can be multiple atoms with the same x.

**Comment by pierrehirel** [comment] 2020-01-06 12:53
Dear jfikar,

Indeed, it is a consequence of parallelization, where each thread (each CPU core) performs a task independently from the others.

The way I see it, this is not a bug. If I modify the code so that atoms appear in a given order, then it means that CPU cores will be allowed to write their atom positions in a specific order, thus loosing all gain of efficiency of the parallelization.

So, you have to choose between efficiency at the cost of reproducibility (atoms should still be at the same positions, but not in the same order), or reproducibility at the cost of efficiency (use only one thread should produce exactly the same ordering of atoms every time). I don't know any method that would keep good efficiency, and produce the same ordering of atoms.

As a side note: to use a single thread you can either set the environment variable "OMP_NUM_THREADS=1", or use the command-line "-nthreads 1" when running Atomsk.

Best regards

**Comment by jfikar** [comment] 2020-01-08 16:08
I see, thank you for explaining the problem.

Is there a way to first sort the atoms by **x** like `-sort x`, but when there are more atoms with the same **x**, sort these atoms by **y** and finally if there is a subset of atoms with the same **x** and **y**, sort them by **z**? It would be sane, as there should not be two atoms with all coordinates equal.

**Comment by pierrehirel** [comment] 2020-01-10 11:56
Sorting by Z, then by Y, and finally by X should do the trick, something like:

`-sort Z up -sort Y up -sort X up`

Nonetheless, if many atoms share an exactly identical coordinate, the order may differ. Atomsk uses quicksort, which splits the list in several pieces. Depending on the size of the list and the split, atoms that have exactly the same coordinate may appear in a different order.

In the end, using a single thread when constructing a polycrystal seems more reliable if you want to have exactly the same order of atoms.

**Comment by pierrehirel** [comment] 2020-02-17 14:31
In absence of reply or comment for over 1 month I close this issue.

**Closed by pierrehirel** 2020-02-17 14:31 UTC
Labels: Question
