### ISSUE TITLE
segmentation fault and stack smashing error

### ISSUE THREAD

**Issue by nokyantenna** [pierrehirel/atomsk#14] opened 2019-10-23 09:37 UTC
Hello, I am getting a "stack smashing detected" message or "segmentation fault" when I try deleting atoms at grain boundary using the 'remove-doubles command. I am running this on cluster with about 5 million atoms in the polycrystal. Here's a screenshot of the error (below).
I appreciate any help I can get on this.
Thank you.

![Screen Shot 2019-10-22 at 4 45 45 PM](https://user-images.githubusercontent.com/35554717/67379544-ee387b80-f53d-11e9-900a-b378c3c649cc.png)

**Comment by pierrehirel** [comment] 2019-10-23 11:47
Dear nokyantenna,

Thank you for reporting this bug. It seems to be caused by a mistake when parallelizing the neighbor search routine.

I just updated the master version, you may download it and try again when you have time. Please report here if the problem is really fixed or not.

Thank you

**Comment by nokyantenna** [comment] 2019-11-26 21:00
Dear Pierre,
Thank you. I was able to download and re-install.
I do have a problem with polycrystal creation on the HPC. I have had
success using the same files on my desktop but getting errors running it
now on HPC.
Here is the note from the webpage, my input file and the error below.
I have also used echo "box 400 400 5.4052" > polycrystal.txt
Thank you and I appreciate your help and time.

Cordially,
Magdalene

[image: Screen Shot 2019-11-26 at 12.55.05 PM.png]

[image: Screen Shot 2019-11-26 at 12.49.44 PM.png]

[image: Screen Shot 2019-11-26 at 12.57.51 PM.png]

On Wed, Oct 23, 2019 at 4:47 AM Pierre Hirel <notifications@github.com>
wrote:

> Dear nokyantenna,
>
> Thank you for reporting this bug. It seems to be caused by a mistake when
> parallelizing the neighbor search routine.
>
> I just updated the master version, you may download it and try again when
> you have time. Please report here if the problem is really fixed or not.
>
> Thank you
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pierrehirel_atomsk_issues_14-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAIPILHOLPKBSZXJGYEK3I7TQQA2WRA5CNFSM4JD6TLBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECBDRUY-23issuecomment-2D545405139&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=xHc_5xOitUYKGUU0XcWh9g&m=-D4O4ma8jF1ng7iMmWh91cxsQVYcZpFbALO9YKsPPnU&s=yQZ-1W3hgzumXAm-FzZtkKy5iwOD1w9-fGdAApSMjs8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIPILHKYCWFUWQVZJE5ZEI3QQA2WRANCNFSM4JD6TLBA&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=xHc_5xOitUYKGUU0XcWh9g&m=-D4O4ma8jF1ng7iMmWh91cxsQVYcZpFbALO9YKsPPnU&s=WfJEKxifruVxEXTA0QyHtIWZHx0QHHNK6Aku2SBjzNM&e=>
> .
>


-- 
GBU
Cordially,

*Ante, Magdalene Anthony*
Ph.D. Candidate, Petroleum Engineering
M.S. Student Computer Science
M.S. Petroleum Engineering (Smart Oilfield Technologies)
Viterbi School of Engineering
University of Southern California
925 Bloom Walk, HED 309
Los Angeles, CA 90089
(469) 328-2224
*"Not by might nor by power, but by my Spirit"*

**Comment by pierrehirel** [comment] 2019-11-28 10:24
Since the current issue is fixed, I close this thread.

Concerning the grain overlapping issue, please use the other thread ( #16 ). Note that I just committed a new version to Github, please test it to see if it solves your issue.

If your problem is different, please open a new thread.

**Closed by pierrehirel** 2019-11-28 10:24 UTC
Labels: Bug
